#
# Module manifest for module 'DefenderASR'
#
# Generated by: Sass, David
#
# Generated on: 6/9/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DefenderASR.psm1'

# Version number of this module.
ModuleVersion = '0.0.4'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '3818f438-f429-4b38-bf21-4ffb4b046180'

# Author of this module
Author = 'Sass, David'

# Company or vendor of this module
CompanyName = 'KolisLab'

# Copyright statement for this module
Copyright = '(c) 2019 Sass, David. All rights reserved.'

# Description of the functionality provided by this module
Description = "This modules was created to help manually configure the local ASR settings of a machine in a small scale scenario where doesn't make sence to use System Center Configuration Manager, Microsoft Intune or Group Policies to deploy the settings."

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("Defender")

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @("Get-DefenderAsrRule","Show-DefenderAsrRule","Backup-DefenderAsrSetting")

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
# AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("MicrosoftDefender", "Defender", "DefenderASR", "DefenderATP", "ATP", "WindowsDefender")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/sassdawe/HardenWindows/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/sassdawe/HardenWindows/tree/master/WindowsDefender/DefenderASR'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'New feature Backup-DefenderAsrSetting'

        # External Module Dependencies which are not available using the Gallery
        ExternalModuleDependencies = @('Defender')

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


